stages:
  - lint
  - template
  - package

variables:
  HELM_CHART_NAME: my-chart
  HELM_PACKAGE_OUTPUT_DIR: packaged_charts

lint:
  stage: lint
  image: alpine/helm:latest
  script:
    - /usr/bin/helm lint /root/new-helm

template:
  stage: template
  image: alpine/helm:latest
  script:
    - /usr/bin/helm template /root/new-helm

package:
  stage: package
  image: alpine/helm:latest
  before_script:
    - export VERSION=$(git rev-parse --short HEAD)
  script:
    - /usr/bin/helm package --version $VERSION path/to/your/chart -d $HELM_PACKAGE_OUTPUT_DIR
  artifacts:
    paths:
      - $HELM_PACKAGE_OUTPUT_DIR/*.tgz

