name: github actions workflow

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 3.13.0 
      - name: Run Helm Lint
        run: helm lint .

  template:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 3.13.0 

      - name: Run Helm Template
        run: helm template .

  package:
    needs: template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: 3.13.0 

      - name: Package Helm Chart
        run: helm package . --version 1.0.${{ github.run_number }}

  diff:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch changes from pull request branch
        run: git fetch origin pull/${{ github.event.pull_request.number }}/merge:pr_branch
        continue-on-error: true

      - name: Show Helm chart differences
        run: |
          git diff --no-index --name-only HEAD pr_branch/.

